export const SHOW_ADD_TASK_MENU = 'LIST/SHOW_ADD_TASK_MENU';
export const HIDE_ADD_TASK_MENU = 'LIST/HIDE_ADD_TASK_MENU';
export const ADD_NEW_LIST_ITEM = 'LIST/ADD_NEW_LIST_ITEM';
export const REMOVE_LIST_ITEM = 'LIST/REMOVE_LIST_ITEM';
export const SHOW_ADD_CARD = 'TASKS/SHOW_ADD_CARD';
export const HIDE_ADD_CARD = 'TASKS/HIDE_ADD_CARD';