export const SHOW_ADD_TASK_MENU = 'LIST/SHOW_ADD_TASK_MENU';
export const HIDE_ADD_TASK_MENU = 'LIST/HIDE_ADD_TASK_MENU';
export const SHOW_ADD_CARD = 'TASKS/SHOW_ADD_CARD';
export const HIDE_ADD_CARD = 'TASKS/HIDE_ADD_CARD';